name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Step 1: Checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Generate metadata for Docker image tags
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: faisalriazawan/guess-meme # Update to your Docker Hub repository
          tags: |
            type=ref,event=branch
            type=sha

      # Step 3: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          install: true
          driver-opts: |
            image=moby/buildkit:v0.10.6

      # Step 5: Login to Docker Hub using the PAT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: faisalriazawan # Replace with your Docker Hub username
          password: ${{ secrets.GHCR_PAT }}

      # Step 6: Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
