name: CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source code from the GitHub repository
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx with docker-container driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DEOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t faisalriazawan/guess-meme:latest \
            --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Login to Docker Hub for deployment
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DEOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Pull the Docker image from Docker Hub
      - name: Pull Image from Docker Hub
        run: docker pull faisalriazawan/guess-meme:latest

      # Step 3: Delete the old container if it exists
      - name: Delete Old Container
        run: docker rm -f nodejs-app-container || true

      # Step 4: Run the new Docker container
      - name: Run Docker Container
        run: |
          docker run -d -p 5000:5000 --name nodejs-app-container \
            -e MONGOURL=${{ secrets.MONGOURL }} \
            -e TOKEN_KEY=${{ secrets.TOKEN_KEY }} \
            -e SECRET=${{ secrets.SECRET }} \
            -e PUSHER_APP_ID=${{ secrets.PUSHER_APP_ID }} \
            -e PUSHER_KEY=${{ secrets.PUSHER_KEY }} \
            -e PUSHER_SECRET=${{ secrets.PUSHER_SECRET }} \
            -e PUSHER_CLUSTER=${{ secrets.PUSHER_CLUSTER }} \
            -e REACT_APP_HELEIUS=${{ secrets.REACT_APP_HELEIUS }} \
            -e INFURA_URL_TESTNET=${{ secrets.INFURA_URL_TESTNET }} \
            -e WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }} \
            -e WALLET_SECRET=${{ secrets.WALLET_SECRET }} \
            -e CONTRACT_ADDRESS=${{ secrets.CONTRACT_ADDRESS }} \
            -e USER_WALLET=${{ secrets.USER_WALLET }} \
            -e TRON_CONTRACT_ADDRESS=${{ secrets.TRON_CONTRACT_ADDRESS }} \
            -e TRON_SECRET=${{ secrets.TRON_SECRET }} \
            -e TRON_RPC=${{ secrets.TRON_RPC }} \
            -e TRON_USER_WALLET=${{ secrets.TRON_USER_WALLET }} \
            -e HALF_MARK=${{ secrets.HALF_MARK }} \
            faisalriazawan/guess-meme:latest
