name: CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source code from the GitHub repository
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx with docker-container driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      # Step 3: Login to Docker Hub using secrets
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DEOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 4: Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t faisalriazawan/guess-meme:latest \
            --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Login to Docker Hub for deployment
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DEOCKER_USER_NAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Step 2: Pull the Docker image from Docker Hub
      - name: Pull Image from Docker Hub
        run: docker pull faisalriazawan/guess-meme:latest

      # Step 3: Delete the old container if it exists
      - name: Delete Old Container
        run: docker rm -f nodejs-app-container || true

      # Step 4: Run the new Docker container
      - name: Run Docker Container
        run: |
          docker run -d \
            -p 5000:5000 \
            --name nodejs-app-container \
            faisalriazawan/guess-meme:latest
