name: CICD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the source code from the GitHub repository
      - name: Checkout source
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx with docker-container driver
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container

      # Step 3: Login to Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DEOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Inject .env variables securely using GitHub secrets
      - name: Set up Environment Variables
        run: echo "${{ secrets.ENV_FILE }}" > .env

      # Step 5: Build Docker image with Buildx caching for faster builds
      - name: Build and Push Docker Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --cache-from type=registry,ref=ghcr.io/faisalriazawan/guess-meme:cache \
            --cache-to type=registry,ref=ghcr.io/faisalriazawan/guess-meme:cache,mode=max \
            -t faisalriazawan/guess-meme:latest \
            --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Login to Docker Hub for deployment
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DEOCKER_USER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Step 2: Pull the latest Docker image from Docker Hub (using cache)
      - name: Pull Image from Docker Hub
        run: docker pull faisalriazawan/guess-meme:latest

      # Step 3: Delete the old container if it exists (improves reliability)
      - name: Delete Old Container (if exists)
        run: |
          docker ps -aq --filter "name=nodejs-app-container" | grep -q . && docker rm -f nodejs-app-container || echo "No container to remove"

      # Step 4: Run Docker Container
      - name: Run Docker Container
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          docker run -d \
            -p 5000:5000 \
            --name nodejs-app-container \
            --env-file .env \
            faisalriazawan/guess-meme:latest
