name: CICD

on:
  push:
    branches:
      - main

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 30
    steps:
      # Step 1: Checkout the source code
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Docker version and info (for debugging)
      - name: Docker version and info
        run: |
          docker version
          docker info

      # Step 3: Generate metadata for Docker image tags
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: faisalriazawan/guess-meme # Update to your Docker Hub image repository
          tags: |
            type=ref,event=branch
            type=sha

      # Step 4: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Step 5: Set up Docker Buildx with buildkit driver for multi-platform support
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: buildkit  # Enable buildkit for multi-platform builds
          install: true
          driver-opts: |
            image=moby/buildkit:v0.10.6  # Use BuildKit image

      # Step 6: Create Buildx builder instance (if not automatically created)
      - name: Create Buildx builder
        run: |
          docker buildx create --use

      # Step 7: Login to Docker Hub using your PAT
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: faisalriazawan  # Docker Hub Username
          password: ${{ secrets.GHCR_PAT }} # GitHub Secret for Docker Hub PAT

      # Step 8: Build and push the Docker image
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
